name: Build Mihon Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Kotlin Linter
        uses: jmailen/kotlinter-gradle@v3
        with:
          gradle-wrapper: ./gradlew

      - name: Run Kotlinter Format
        run: ./gradlew ktlintFormat

      - name: Build 24hNovel extension (RELEASE)
        run: ./gradlew :src:all:twentyfourhnovel:assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: twentyfourhnovel-release-apk
          path: src/all/twentyfourhnovel/build/outputs/apk/release/*.apk
